### ISSUE TITLE
What am I'm doing wrong here?

### ISSUE THREAD

**Issue by dannymertens** [arjhun/Homeassistant-Lovelace-Cards#2]
Hi, I think that I did everything that is described but still it does not work, any idea what I'm doning wrong, sorry very new in this so probably something stupid from my side ;-)

Thanks!

![image](https://user-images.githubusercontent.com/46963011/78270501-31464400-750b-11ea-93c9-4489bca5035f.png)

```
type: 'custom:simple-clock-card'
use_military: false
hide_seconds: false
```
![image](https://user-images.githubusercontent.com/46963011/78270687-75d1df80-750b-11ea-9ba4-04bf3d0bff6f.png)

![image](https://user-images.githubusercontent.com/46963011/78270425-196ec000-750b-11ea-9694-162a165226bd.png)

**Comment by arjhun** [comment]
Hi Danny, 

you have to put the whole `simple-clock-card` folder in `www/elements/
`

**Comment by fufar** [comment]
same problem, @arjhun

**Comment by Benz01877** [comment]
Same problem...

**Comment by arjhun** [comment]
Hello everybody, I've updated the configuration to make the installation more clear. Let me know if you can make it work now!

**Comment by fufar** [comment]
how about hacs integration?

**Comment by arjhun** [comment]
> how about hacs integration?

That's beyond the scope of what I was trying to achieve. But you are free to fork this script and implement it yourself! Good luck!.

**Comment by arjhun** [comment]
I consider this closed

**Comment by fufar** [comment]
made fork easy hacs installation, hope it will be helpful for someone
https://github.com/fufar/simple-clock-card
