### ISSUE TITLE
something is wrong with this repo

### ISSUE THREAD

**Issue by branitelj91** [arjhun/Homeassistant-Lovelace-Cards#3]
Repo installed through HACS  but lovelace moans of nonexistant card. 
in the resources I find this link:

/hacsfiles/simple-clock-card/simple-clock-card.js?hacstag=34193126615

and js resides in my www folder :

/config/www/community/simple-clock-card

the Home assistant is HASSio on RPI
any advice?

**Comment by arjhun** [comment]
Hi I have no experience with HACS and my simple card was never designed for any automatic installation. You are more than welcome to figure this out. I'll implement the changes if needed. Let me know. 

for manual installation see my guide here 

https://github.com/arjhun/Homeassistant-Lovelace-Cards/tree/master/simple-clock-card

for HACS i see that somebody made a repo that maybe works?

https://github.com/fufar/simple-clock-card by @fufar
